{% set name = "typish" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ramonhagenaars/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d0f8e0dc2161fbe24fba50177e1beaa29d9b811d6374fdcc5af48dd4a5b135db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - typish
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramonhagenaars/typish
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: For more control over your types.

  description: |
    For more control over your types.
  doc_url: https://github.com/ramonhagenaars/typish
  dev_url: https://github.com/ramonhagenaars/typish

extra:
  recipe-maintainers:
    - jan-janssen
