{% set name = "typish" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ramonhagenaars/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e2f270c9d396d47a6e9d4e2a80062025fd03c8f5295d32fd03401450d142121b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - typish
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ramonhagenaars/typish
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: For more control over your types.

  description: |
    For more control over your types.
  doc_url: https://github.com/ramonhagenaars/typish
  dev_url: https://github.com/ramonhagenaars/typish

extra:
  recipe-maintainers:
    - jan-janssen
